server:
  port: 8760

spring:
  application:
    name: zuul

zuul:
  debug:
    request: true
  # 阻止将eureka中的微服务暴露在zuul网关中
  ignored-services: "*"
  routes:
    a:
      path: /a/**
      url: http://www.baidu.com/
      sensitiveHeaders: #留空会将所有请求头转发到后续服务中
    user-service-provider: /up/**
    user-service-invoker: /ui/**

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: ${spring.application.name}
    appname: ${spring.application.name}-app

ribbon:
  eager-load:
    enabled: true

print-server-address:
  ignore-parent-context: true

management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: "*"
