spring:
  application:
    name: user-service-provider

eureka:
  client:
    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/
      defaultZone: http://localhost:8761/eureka/
    # eureka客户端每隔多久去eureka服务器拉取最新的注册信息默认30秒
    registry-fetch-interval-seconds: 10
  instance:
    lease-renewal-interval-in-seconds: 1
    prefer-ip-address: true # 使用ip地址注册
    appname: ${spring.application.name}

server:
  port: 8700

logging:
  level:
    root: INFO
    org:
      springframework:
        web:
          servlet:
            DispatcherServlet: DEBUG
  file: user-service-invoker.log

print-server-address:
  ignore-parent-context: true

info:
  tags:
    environment: test
  app: ${spring.application.name}

management:
  endpoints:
    web:
      exposure:
        include: "*"