spring:
  application:
    name: user-service-provider

eureka:
  client:
    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/
      defaultZone: http://localhost:8761/eureka/
  instance:
    lease-renewal-interval-in-seconds: 1
    prefer-ip-address: true # 使用ip地址注册
    appname: ${spring.application.name}

server:
  port: 8700

logging:
  level:
    root: INFO
    org:
      springframework:
        web:
          servlet:
            DispatcherServlet: DEBUG

print-server-address:
  ignore-parent-context: true

info:
  app: ${spring.application.name}