spring:
  application:
    name: user-service-provider-2
  profiles:
    active: dev

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    appname: ${spring.application.name}

server:
  port: 8801

logging:
  level:
    root: INFO

print-server-address:
  ignore-parent-context: true

info:
  app: ${spring.application.name}

management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: "*"