server:
  port: 8761

spring:
  application:
    name: eureka-server

eureka:
  client:
    register-with-eureka: false #不向eureka注册自己
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    appname: ${spring.application.name}
  server:
    waitTimeInMsWhenSyncEmpty: 0

logging:
  level:
    root: INFO

print-server-address:
  ignore-parent-context: true

info:
  app: ${spring.application.name}