server:
  port: 8762

spring:
  application:
    name: eureka-server-2

eureka:
  client:
    register-with-eureka: false #不向eureka注册自己
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8761
  instance:
    appname: eureka-server-2
  server:
    waitTimeInMsWhenSyncEmpty: 0

logging:
  level:
    root: INFO

print-server-address:
  ignore-parent-context: true

info:
  app: ${spring.application.name}