server:
  port: 8762

spring:
  application:
    name: eureka-server-1

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8762
  instance:
    appname: ${spring.application.name}
  server:
    waitTimeInMsWhenSyncEmpty: 0